__title__ = "lpipe"
__version__ = "4.1.0"
__summary__ = "AWS Lambda framework for writing clear, minimal Python FAAS"
__author__ = "Charlie Mathews"
__author_email__ = "cmathews@mintel.com"
__maintainer__ = "Charlie Mathews"
__maintainer_email__ = "cmathews@mintel.com"
__uri__ = "https://github.com/mintel/lpipe"
