__title__ = "lpipe"
__version__ = "2.0.26"
__summary__ = "Lambda toolkit and message pipeline."
__author__ = "Charlie Mathews"
__author_email__ = "cmathews@mintel.com"
__maintainer__ = "Charlie Mathews"
__maintainer_email__ = "cmathews@mintel.com"
__uri__ = "https://github.com/mintel/lpipe"
